name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'bugfix'
      - 'hotfix'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🧪 Tests'
    labels:
      - 'test'
      - 'tests'
  - title: '🧹 Chores'
    labels:
      - 'chore'
      - 'dependencies'
      - 'maintenance'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\\<*_&' # You can add # and \ to escape markdown syntax in commit messages
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
  default: patch

template: |
  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS

  ### Full Changelog
  $CHANGES_WITHOUT_CATEGORIES

replacers:
  - search: '/<!-- RELEASE_DRAFTER_START -->[\s\S]*<!-- RELEASE_DRAFTER_END -->/g'
    replace: ''
  - search: '/(#\d+)/g'
    replace: '[#$1](https://github.com/$GITHUB_REPOSITORY/issues/$1)'
  - search: '/@(\w+)/g'
    replace: '[@$1](https://github.com/$1)'

exclude-labels:
  - 'skip-changelog'
  - 'duplicate'
  - 'question'
  - 'invalid'
  - 'wontfix'
  - 'rfc'
  - 'dependencies'
