"""fix_build_professions_primary_key

Revision ID: 0cad28c6411f
Revises: a9e182a70b39
Create Date: 2025-09-08 18:05:36.975054+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0cad28c6411f"
down_revision: Union[str, Sequence[str], None] = "a9e182a70b39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "professions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("icon_url", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("game_modes", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_professions_id"), "professions", ["id"], unique=False)
    op.create_index(op.f("ix_professions_name"), "professions", ["name"], unique=True)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("permission_level", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "builds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("game_mode", sa.String(), nullable=False),
        sa.Column("team_size", sa.Integer(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("constraints", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_builds_id"), "builds", ["id"], unique=False)
    op.create_index(op.f("ix_builds_name"), "builds", ["name"], unique=False)
    op.create_table(
        "elite_specializations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("profession_id", sa.Integer(), nullable=False),
        sa.Column("icon_url", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["profession_id"],
            ["professions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_elite_specializations_id"),
        "elite_specializations",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_elite_specializations_name"),
        "elite_specializations",
        ["name"],
        unique=False,
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "build_professions",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("profession_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["build_id"], ["builds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["profession_id"], ["professions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint(
            "build_id", "profession_id", name="pk_build_profession"
        ),
    )
    op.create_index(
        op.f("ix_build_professions_id"), "build_professions", ["id"], unique=False
    )
    op.create_table(
        "compositions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("squad_size", sa.Integer(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("build_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["builds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_compositions_id"), "compositions", ["id"], unique=False)
    op.create_index(
        op.f("ix_compositions_name"), "compositions", ["name"], unique=False
    )
    op.create_table(
        "composition_members",
        sa.Column("composition_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("profession_id", sa.Integer(), nullable=True),
        sa.Column("elite_specialization_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["composition_id"],
            ["compositions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["elite_specialization_id"],
            ["elite_specializations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profession_id"],
            ["professions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("composition_id", "user_id"),
    )
    op.create_table(
        "composition_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("composition_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["composition_id"],
            ["compositions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_composition_tags_id"), "composition_tags", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_composition_tags_name"), "composition_tags", ["name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_composition_tags_name"), table_name="composition_tags")
    op.drop_index(op.f("ix_composition_tags_id"), table_name="composition_tags")
    op.drop_table("composition_tags")
    op.drop_table("composition_members")
    op.drop_index(op.f("ix_compositions_name"), table_name="compositions")
    op.drop_index(op.f("ix_compositions_id"), table_name="compositions")
    op.drop_table("compositions")
    op.drop_index(op.f("ix_build_professions_id"), table_name="build_professions")
    op.drop_table("build_professions")
    op.drop_table("user_roles")
    op.drop_index(
        op.f("ix_elite_specializations_name"), table_name="elite_specializations"
    )
    op.drop_index(
        op.f("ix_elite_specializations_id"), table_name="elite_specializations"
    )
    op.drop_table("elite_specializations")
    op.drop_index(op.f("ix_builds_name"), table_name="builds")
    op.drop_index(op.f("ix_builds_id"), table_name="builds")
    op.drop_table("builds")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_professions_name"), table_name="professions")
    op.drop_index(op.f("ix_professions_id"), table_name="professions")
    op.drop_table("professions")
    # ### end Alembic commands ###
