name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  update_release_draft:
    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
        with:
          path: './package.json'

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          name: 'Release ${{ steps.package-version.outputs.current-version }}'
          tag: 'v${{ steps.package-version.outputs.current-version }}'
          version: '${{ steps.package-version.outputs.current-version }}'
          publish: true
          prerelease: ${{ !contains(github.ref, 'refs/heads/main') }}
          config-name: 'release-drafter.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
