name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  stale:
    name: Mark stale issues and pull requests
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Mark issues and pull requests as stale
        uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 60
          days-before-close: 7
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions!'
          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions!'
          close-issue-message: 'This issue has been automatically closed due to inactivity. If you believe this was closed in error, please open a new issue.'
          close-pr-message: 'This pull request has been automatically closed due to inactivity. If you believe this was closed in error, please reopen or create a new pull request.'
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security,bug,enhancement,documentation,good first issue,help wanted,priority: high,priority: critical,status: blocked,status: in progress,status: on hold,type: bug,type: documentation,type: enhancement,type: feature,type: question,type: support,type: discussion'
          stale-pr-label: 'stale'
          exempt-pr-labels: 'pinned,security,bug,enhancement,documentation,good first issue,help wanted,priority: high,priority: critical,status: blocked,status: in progress,status: on hold,type: bug,type: documentation,type: enhancement,type: feature,type: question,type: support,type: discussion,status: needs review,status: changes requested,status: ready for review,status: work in progress,status: needs testing,status: needs update,status: needs rebase,status: needs revision,status: needs approval,status: needs merge,status: needs rebase,status: needs update,status: needs revision,status: needs approval,status: needs merge'
          operations-per-run: 100
          remove-stale-when-updated: true
          remove-issue-stale-when-updated: true
          remove-pr-stale-when-updated: true
          debug-only: false
