name: Backend Test & Coverage

on:
  push:
    branches: [main, develop]
    paths:
      - 'backend/**'
      - '.github/workflows/test-and-coverage.yml'
      - 'pyproject.toml'
      - 'poetry.lock'
  pull_request:
    branches: [main, develop]
    paths:
      - 'backend/**'
      - '.github/workflows/test-and-coverage.yml'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  test:
    name: Test and Coverage
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev python3-dev python3-pip
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.5.1
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry config virtualenvs.create true
          
      - name: Install dependencies
        working-directory: ./backend
        run: |
          cd backend
          # Install dependencies in one go to avoid timeouts
          poetry add email-validator itsdangerous python-json-logger pytest-asyncio pytest-trio pytest-mock pytest-cov codecov pytest-factoryboy --group dev --no-interaction
          # Install the project in development mode with all extras
          poetry install --no-interaction --no-ansi --with dev
          # Initialize test database
          poetry run alembic upgrade head

      - name: Cache Poetry virtualenv
        id: cache-venv
        uses: actions/cache@v3
        with:
          path: ./backend/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Set up test database
        working-directory: ./backend
        run: |
          # Create test database and run migrations
          export DATABASE_URL=sqlite:///./test.db
          poetry run alembic upgrade head

      - name: Run tests with coverage
        working-directory: ./backend
        env:
          DATABASE_URL: sqlite:///./test.db
          PYTHONPATH: ${{ github.workspace }}/backend
          COVERAGE_FILE: ${{ github.workspace }}/backend/.coverage
        run: |
          mkdir -p test-results
          set -o pipefail
          poetry run pytest tests/ \
            -v \
            --asyncio-mode=auto \
            --cov=app \
            --cov-report=xml:coverage.xml \
            --cov-report=html:htmlcov \
            --cov-report=term-missing \
            --cov-fail-under=90 \
            --junitxml=test-results/junit.xml \
            --log-cli-level=INFO \
            2>&1 | tee test-results/pytest.log

      - name: Upload coverage to Codecov
        if: success() && github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN || '' }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            ./backend/test-results/
            ./backend/coverage.xml
          retention-days: 7

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: |
            ./backend/coverage.xml
            ./backend/htmlcov/
          retention-days: 30

      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs
          path: |
            ./backend/test-results/pytest.log
            ./backend/.pytest_cache/
          retention-days: 1
